version: '3'

tasks:
  check:
    cmds:
      - go build -v -o /dev/null pkg/*/*

  installdeps:
    cmds:
      - go mod tidy -go=1.16

  test:
    cmds:
      - go test -v pkg/*/*.go
    env:
      LOGFILEPATH: "/tmp/test.log"

  docker:
    cmds:
      - docker run -t -v `pwd`:/app/test amerigal/gestor-recibos

  build:
    cmds:
  
  install:
    cmds: