version: '3'

tasks:
  check:
    cmds:
      - go build -v -o /dev/null pkg/*/*

  installdeps:
    cmds:
      - go mod tidy

  test:
    cmds:
      - go test -v pkg/*/*.go

  docker:
    cmds:
      - docker run -t -v `pwd`:/app/test amerigal/gestor-recibos