version: 2.1

jobs:
  test_language_version:
      parameters:
        version:
          type: string
      docker:
        - image: cimg/go:<< parameters.version >>
          auth:
            username: "$secrets.DOCKER_HUB_USER"
            password : "$secrets.DOCKER_HUB_PASSWORD"
      steps:
        - checkout
        - run: go build -v -o /dev/null pkg/*/*

  test:
    machine:
        image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: docker run -t -v `pwd`:/app/test amerigal/gestor-recibos

workflows:
  test_and_versions:
    jobs:
      - test_language_version:
          matrix:
            parameters:
              version: ["1.16", "1.17"]
      - test
