name: Depligue Automático de Contenedor

on:
  push:
    branches:
      - 'main'

env:
  USER: ${{ secrets.DOCKER_HUB_USER }}
  PSSW: ${{ secrets.DOCKER_HUB_PASSWORD }}
  REPO: gestor-recibos

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@v2

      -name: Instalación Docker
       uses: docker/setup-buildx-action@v1

      -name: Acceso a Docker
       run: docker login --username=$USER --password=$PSSW

      -name: Build
       run: docker build -t $USER/$REPO:latest .
       
      -name: Push
       run: docker push $USER/$REPO:latest